### ISSUE TITLE
Do not treat escaped | as table cell separator

### ISSUE THREAD

**Issue by robertomier** [rmescandon/gherkiner#6]
table columns separator must not be considered when escaped

<img width="799" alt="image" src="https://github.com/rmescandon/gherkiner/assets/61735382/50e3383b-46b1-4bd6-9eb4-a970bc95a4e7">

when found **\\|** it should not be considered as a table cell separator, but it does and breaks the document format

**Comment by rmescandon** [comment]
Fixed on release 1.0.2
